civicart/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from artworks import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/profile', views.profile),
    url(r'^artwork/(?P<id>[\w-]+)$', views.artwork, name='artwork'),
    url(r'^artwork/(?P<id>[\w-]+)/adopt/$', views.adopt, name='adopt'),
    url(r'^artwork/(?P<id>[\w-]+)/tip/$', views.tip, name='tip'),
    url(r'^artwork/(?P<id>[\w-]+)/unadopt/$', views.unadopt),
    url(r'^artwork/(?P<id>[\w-]+)/check-in/$', views.checkin, name='checkin'),
    url(r'^artworks/$', views.artworks),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

artworks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin


class AboutPage(models.Model):
    first_row_header = models.CharField(max_length=200, blank=True)
    first_row_text = models.TextField(blank=True)
    second_row_header = models.CharField(max_length=200, blank=True)
    second_row_column_one_header = models.CharField(max_length=200, blank=True)
    second_row_column_one_text = models.TextField(blank=True)
    second_row_column_two_header = models.CharField(max_length=200, blank=True)
    second_row_column_two_text = models.TextField(blank=True)
    second_row_column_three_header = \
        models.CharField(max_length=200, blank=True)
    second_row_column_three_text = models.TextField(blank=True)
    call_to_action_text = models.TextField(blank=True)
    call_to_action_button = models.CharField(max_length=200, blank=True)
    call_to_action_link = models.CharField(max_length=200, blank=True)

    class Meta:
        verbose_name_plural = 'About Page'

    def __str__(self):
        return 'About Page'


class ArtworkImage(models.Model):
    artwork = models.ForeignKey('Artwork')
    image = models.ImageField(
        upload_to='artworks/',
        blank=False,
        help_text='Image file upload size limit is 2.5MB.'
    )
    url = models.CharField(max_length=200, blank=True)
    license = models.CharField(max_length=200, blank=True)
    caption = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.artwork.title


class ArtworkType(models.Model):
    artwork_type = models.CharField(max_length=200)

    class Meta:
        ordering = ['artwork_type']
        verbose_name = 'Artwork Type'
        verbose_name_plural = 'Artwork Type List'

    def __str__(self):
        return self.artwork_type


class ArtworkMedium(models.Model):
    medium = models.CharField(max_length=200)

    class Meta:
        ordering = ['medium']
        verbose_name = 'Artwork Medium'
        verbose_name_plural = 'Artwork Medium List'

    def __str__(self):
        return self.medium


class Artwork(models.Model):
    title = models.CharField(max_length=200, blank=False)
    description = models.TextField(blank=False)
    lat = models.FloatField(blank=False)
    lon = models.FloatField(blank=False)
    artist_name = models.CharField(max_length=200, blank=False)
    creation_date = models.IntegerField(
        blank=False,
        help_text='Enter a year in YYYY format, like 1978 or 2017',
        null=True)
    date_description = models.TextField(blank=True)
    show_date_description = models.BooleanField(
        default=False,
        blank=False,
        help_text='Checking this will show the date description \
        instead of creation date on the artwork page')
    artwork_type = models.ManyToManyField(ArtworkType)
    medium = models.ManyToManyField(ArtworkMedium)
    location_name = models.CharField(max_length=200, blank=False)
    street_1 = models.CharField(max_length=200, blank=True)
    street_2 = models.CharField(max_length=200, blank=True)
    city = models.CharField(max_length=200, blank=False)
    zipcode = models.IntegerField(blank=False)
    date_entered = models.DateTimeField(auto_now_add=True, null=True)
    active = models.BooleanField(default=True, blank=False)

    def __str__(self):
        return self.title


class Adoption(models.Model):
    user = models.ForeignKey(User)
    artwork = models.ForeignKey('Artwork')
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.artwork.title


class Tip(models.Model):
    artwork = models.ForeignKey('Artwork')
    timestamp = models.DateTimeField(auto_now_add=True)
    condition = models.TextField(blank=False)


class CheckinImage(models.Model):
    checkin = models.ForeignKey('Checkin')
    image = models.ImageField(upload_to='checkins/', blank=False)
    status = models.CharField(
        max_length=100, blank=True, choices=[
            ('H', 'High Priority'),
            ('L', 'Low Priority'),
            ('A', 'Archived'),
            ('R', 'Reviewed'),
        ])
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Check In Photos'

    def __str__(self):
        return 'Check In Photo'


class CheckinDamage(models.Model):
    damage = models.CharField(max_length=200)

    class Meta:
        verbose_name = 'Check In Damage Description'

    def __str__(self):
        return self.damage


class Checkin(models.Model):
    user = models.ForeignKey(User)
    artwork = models.ForeignKey('Artwork')
    condition = models.CharField(
        max_length=100, blank=False, choices=[
            ('G', 'Good Condition'),
            ('D', 'Damaged'),
        ])
    damage = models.ManyToManyField(CheckinDamage, blank=True)
    damaged_description = models.TextField(blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Check In'

    def __str__(self):
        return self.artwork.title

artworks/forms.py
from django import forms
from django.forms import ModelForm
from artworks.models import Tip, Checkin, CheckinImage, CheckinDamage


class CheckinForm(ModelForm):
    condition = forms.ChoiceField(
      widget=forms.RadioSelect,
      choices=[
        ('G', 'Good Condition'),
        ('D', 'Damaged')],
      label='What\'s the current condition of the artwork?'
    )
    damage = forms.ModelMultipleChoiceField(
      widget=forms.CheckboxSelectMultiple,
      queryset=CheckinDamage.objects.all(),
      required=False,
      label=''
    )
    damaged_description = forms.CharField(
      widget=forms.Textarea,
      required=False,
      label='What kind of damage do you see?'
    )

    class Meta:
        model = Checkin
        fields = ('condition', 'damage', 'damaged_description')


class CheckinImageForm(ModelForm):
    class Meta:
        model = CheckinImage
        fields = ('image', )


class TipForm(forms.Form):
    condition = forms.CharField(
      widget=forms.Textarea,
      required=True
    )

artworks/views.py
from django.conf import settings
from django.shortcuts import get_object_or_404, render, redirect

from django.core.exceptions import ObjectDoesNotExist

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from django.forms import modelformset_factory

from artworks.models import AboutPage, Artwork, Adoption, Tip, Checkin, CheckinImage
from artworks.forms import CheckinForm, CheckinImageForm, TipForm


def index(request):
    artworks = Artwork.objects.order_by('-id').filter(active=True)

    return render(request, 'index.html', {
        'artworks': artworks,
        'GOOGLE_MAPS_API_KEY': settings.GOOGLE_MAPS_API_KEY
    })


def about(request):
    about = AboutPage.objects.last()

    return render(request, 'about.html', {
        'about': about
    })


def artwork(request, id):
    artwork = get_object_or_404(Artwork, pk=id)

    adoptees = Adoption.objects.filter(artwork=artwork)

    last_checkin = Checkin.objects.filter(artwork=artwork) \
        .order_by('-timestamp')[:1]

    if request.user.is_authenticated:
        adopted = Adoption.objects.filter(user=request.user, artwork=artwork)
    else:
        adopted = False

    return render(request, 'artwork.html', {
        'artwork': artwork,
        'adoptees': adoptees,
        'last_checkin': last_checkin,
        'adopted': adopted
    })


def artworks(request):
    artworks = Artwork.objects.order_by('-id').filter(active=True)

    return render(request, 'artworks.html', {
        'artworks': artworks,
    })


@login_required
def profile(request):
    adoptions = Adoption.objects.filter(user=request.user)

    return render(request, 'registration/profile.html', {
        'adoptions': adoptions
    })


@login_required
def adopt(request, id):
    artwork = get_object_or_404(Artwork, pk=id)
    adoptees = Adoption.objects.filter(artwork=artwork)

    check_adopted = Adoption.objects.filter(user=request.user, artwork=artwork)

    if not check_adopted:
        adopt = Adoption(user=request.user, artwork=artwork)
        adopt.save()

    adopted = True

    return render(request, 'artwork.html', {
        'artwork': artwork,
        'adoptees': adoptees,
        'adopted': adopted
    })


@login_required
def unadopt(request, id):
    artwork = Artwork.objects.filter(id=id)

    Adoption.objects.filter(user=request.user, artwork=artwork).delete()

    adoptions = Adoption.objects.filter(user=request.user)

    return render(request, 'registration/profile.html', {
        'adoptions': adoptions
    })


@login_required
def checkin(request, id):
    artwork = Artwork.objects.get(id=id)

    # https://stackoverflow.com/questions/34006994/how-to-upload-multiple-images-to-a-blog-post-in-django

    CheckinImageFormSet = modelformset_factory(
        CheckinImage,
        form=CheckinImageForm,
        min_num=1,
        max_num=3,
        extra=3
    )

    if request.method == 'POST':
        checkinForm = CheckinForm(request.POST)
        formset = CheckinImageFormSet(
            request.POST,
            request.FILES,
            queryset=CheckinImage.objects.none())

        if checkinForm.is_valid() and formset.is_valid():
            checkin = checkinForm.save(commit=False)
            checkin.user = request.user
            checkin.artwork = artwork

            checkin.save()
            # Save check in damage many to many checkboxes
            checkinForm.save_m2m()

            photos = formset.save(commit=False)

            for photo in photos:
                photo.checkin = checkin
                photo.save()

            return redirect('artwork', id=artwork.id)
        else:
            formErrors = formset.errors

            return render(request, 'check-in.html', {
                'artwork': artwork,
                'checkinForm': checkinForm,
                'formset': formset,
                'formErrors': formErrors
            })

    else:
        checkinForm = CheckinForm()
        formset = CheckinImageFormSet(queryset=CheckinImage.objects.none())

    return render(request, 'check-in.html', {
        'artwork': artwork,
        'checkinForm': checkinForm,
        'formset': formset
    })


def tip(request, id):
    artwork = Artwork.objects.get(id=id)

    if request.user.is_authenticated():
        return render(request, 'artwork.html', {
            'artwork': artwork,
        })

    if request.method == 'POST':
        form = TipForm(request.POST)

        if form.is_valid():
            tip = Tip(artwork=artwork, condition=form.cleaned_data['condition'])
            tip.save()

            return render(request, 'artwork.html', {
                'artwork': artwork,
                'tipSubmitted': True
            })
    else:
        form = TipForm

    return render(request, 'submit-a-tip.html', {
        'artwork': artwork,
        'form': form
    })


def handler404(request):
    response = render_to_response('404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 404
    return response


def handler500(request):
    response = render_to_response('500.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 500
    return response

artworks/templates/about.html
{% extends "base.html" %}

{% block title %}About Adoption{% endblock title %}

{% block content %}

  <div id="about">

    <section class="first-row">
      <h2>{{ about.first_row_header }}</h2>
      <p>{{ about.first_row_text }}</p>
    </section>

    <section class="second-row">
      <h2>{{ about.second_row_header }}</h2>

      <ul>
        <li>
          <h3>{{ about.second_row_column_one_header }}</h3>
          <p>{{ about.second_row_column_one_text }}</p>
        </li>
        <li>
          <h3>{{ about.second_row_column_two_header }}</h3>
          <p>{{ about.second_row_column_two_text }}</p>
        </li>
        <li>
          <h3>{{ about.second_row_column_three_header }}</h3>
          <p>{{ about.second_row_column_three_text }}</p>
        </li>
      </ul>
    </section>

    <section class="third-row">
      <div class="call-to-action">
        <p>{{ about.call_to_action_text }}</p>

        <a href="{{ about.call_to_action_link }}">{{ about.call_to_action_button }}</a>
      </div>
    </section>

  </div>

{% endblock content %}

artworks/templates/artwork.html
{% extends "base.html" %}

{% block title %}{{ artwork.title }}{% endblock title %}

{% block content %}
  <div class="artwork">
    <div class="artwork-image">
    {% with artwork.artworkimage_set.all|first as artwork_image %}
    {% if artwork_image %}
      <img src="{{ MEDIA_URL }}{{ artwork_image.image }}" alt="{{ artwork.description }}">
    {% endif %}
    {% endwith %}
    </div>
    <section>
      <div class="artwork-content">
        <h2>{{ artwork.title }}</h2>
        <div class="artist">{{ artwork.artist_name }}</div>
        <p>{{ artwork.description }}</p>
      </div>

      <aside>
        <ul>
          {% if last_checkin %}
          <li>
            <h4>Last check-in</h4>
            {{ last_checkin.0.timestamp|date:"F j, Y" }} by
            {{ last_checkin.0.user }}
          </li>
          {% endif %}
          {% if adoptees %}
          <li class="adopted">
            <h4>Adopted by</h4>
            <ul>
            {% for adoptee in adoptees %}
              <li>{{ adoptee.user }}</li>
            {% endfor %}
            </ul>
          </li>
          {% endif %}
          <li>
            <h4>Location</h4>
            {{ artwork.location_name }}<br>
            {% if artwork.street_1 %}
              {{ artwork.street_1 }}<br>
            {% endif %}
            {% if artwork.street_2 %}
              {{ artwork.street_2 }}<br>
            {% endif %}
            {{ artwork.city }}<br>
            {{ artwork.zipcode }}<br>
          </li>
        </ul>
        {% if not adopted %}
        <a href="/artwork/{{ artwork.id }}/adopt/">
          <button class="adopt">Adopt Me!</button>
        </a>
        {% if not request.user.is_authenticated %}
        {% if tipSubmitted %}
          Thanks for submitting your tip.
        {% else %}
        <a href="/artwork/{{ artwork.id }}/tip/">
          <button class="tip">Submit a Tip</button>
        </a>
        {% endif %}
        {% endif %}
        {% else %}
        <a href="/artwork/{{ artwork.id }}/check-in/"><button class="check-in">Check In</button></a>
        <a href="/artwork/{{ artwork.id }}/unadopt" class="cancel">Cancel Adoption</a>
        {% endif %}
      </aside>
    </section>

    <div class="details">
      <section>
        <h3>Artwork Details</h3>
        {% if artwork.artwork_type.all %}
        <h4>Artwork Type</h4>
        <p>{{ artwork.artwork_type.all.0 }}</p>
        {% endif %}
        {% if artwork.medium.all %}
        <h4>Medium</h4>
        <p>{{ artwork.medium.all|join:", " }}</p>
        {% endif %}
        <h4>Creation date</h4>
        {% if artwork.show_date_description %}
        <p>{{ artwork.date_description }}</p>
        {% else %}
        <p>{{ artwork.creation_date }}</p>
        {% endif %}
      </section>
    </div>
  </div>
{% endblock content %}

artworks/templates/artworks.html
{% extends "base.html" %}

{% block title %}List of artworks{% endblock title %}

{% block content %}

  <div id="artworks">

    <ul>
    {% for artwork in artworks %}
      <li>
        <a href="/artwork/{{ artwork.id }}">{{ artwork.title }}</a>
      </li>
    {% endfor %}
    </ul>

  </div>

{% endblock content %}

artworks/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>Art Watcher - {% block title %}{% endblock title %}</title>

  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">

  <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,700" rel="stylesheet">
  <link rel="stylesheet" href="{% static "css/styles.css" %}" />
</head>
<body>
  <div class="main">
    {% include "nav.html" %}

    {% block content %}{% endblock content %}
  </div>

  {% block scripts %}{% endblock scripts %}

</body>
</html>

artworks/templates/check-in.html
{% extends "base.html" %}

{% block title %}Check In to {{ artwork.title }}{% endblock title %}

{% block content %}
  <div class="check-in-artwork">

    <div class="details">

      {% if artwork.artworkimage_set.all.0.image %}
        <img src="{{ MEDIA_URL }}{{ artwork.artworkimage_set.all.0.image }}" alt="{{ artwork.description }}">
      {% endif %}

      <h3>{{ artwork.title }}</h3>
      <div class="artist">{{ artwork.artist_name }}</div>
      {{ artwork.location_name }}<br>
      {% if artwork.street_1 %}
        {{ artwork.street_1 }}<br>
      {% endif %}
      {% if artwork.street_2 %}
        {{ artwork.street_2 }}<br>
      {% endif %}
      {{ artwork.city }}<br>
      {{ artwork.zipcode }}<br>

    </div>

    <div class="report">

      <h4>Check In or Report Damage</h4>

      <form class="post-form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <ul>
        {{ checkinForm.as_ul }}
        </ul>

        {{ formset.management_form }}
        {% for form in formset %}
          {{ form }}
        {% endfor %}

        <button type="submit">Submit</button>
      </form>

    </div>

  </div>
{% endblock content %}

artworks/templates/index.html
{% extends "base.html" %}

{% load static %}

{% block title %}Adopt a civic artwork today{% endblock title %}

{% block content %}
  <div id="home">

    <ul class="artworks">
    {% for artwork in artworks %}
      <li data-artwork-id="{{ artwork.id }}" data-artwork-title="{{ artwork.title }}" data-lat="{{ artwork.lat }}" data-lon="{{ artwork.lon }}">
        <a href="/artwork/{{ artwork.id }}">
        <div class="image">
        {% with artwork.artworkimage_set.all|first as artwork_image %}
        {% if artwork_image %}
          <img src="{{ MEDIA_URL }}{{ artwork_image.image }}" alt="{{ artwork.description }}">
        {% endif %}
        {% endwith %}
        </div>
        <div class="info">
          <h2>{{ artwork.title }}</h2>
          <div class="author">{{ artwork.artist_name }}</div>
        </div>
        </a>
      </li>
    {% endfor %}
    </ul>

    <div id="map"></div>

  </div>
{% endblock content %}

{% block scripts %}
  <script src="{% static "js/app.js" %}"></script>
  <script async defer
  src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_MAPS_API_KEY }}&callback=initMap">
  </script>
{% endblock scripts %}

artworks/templates/nav.html
{% load static %}

<nav role="navigation">
  <h1>
    <a href="/">
      <img src="{% static "img/artwatcher.jpg" %}" alt="Artwatcher" class="logo">
      <span>Art Watcher</span>
    </a>
  </h1>
  <ul>
    <li><a href="{% url 'about' %}">About</a></li>
    {% if not request.user.is_authenticated %}
    <li><a href="/accounts/login">Log in</a></li>
    <li class="sign-up"><a href="/accounts/register">Sign up</a></li>
    {% else %}
    <li class="logged-in">Logged in as <a href="/accounts/profile" class="user">{{ user }}</a> (<a href="/accounts/logout">log out</a>)</li>
    {% endif %}
  </ul>
</nav>

artworks/templates/submit-a-tip.html
{% extends "base.html" %}

{% block title %}Submit a Tip for {{ artwork.title }}{% endblock title %}

{% block content %}
  <div class="check-in-artwork">

    <div class="details">

      {% if artwork.artworkimage_set.all.0.image %}
        <img src="{{ MEDIA_URL }}{{ artwork.artworkimage_set.all.0.image }}" alt="{{ artwork.description }}">
      {% endif %}

      <h3>{{ artwork.title }}</h3>
      <div class="artist">{{ artwork.artist_name }}</div>
      {{ artwork.location_name }}<br>
      {% if artwork.street_1 %}
        {{ artwork.street_1 }}<br>
      {% endif %}
      {% if artwork.street_2 %}
        {{ artwork.street_2 }}<br>
      {% endif %}
      {{ artwork.city }}<br>
      {{ artwork.zipcode }}<br>

    </div>

    <div class="report">

      <h4>Submit a Tip</h4>

      {% if form %}
      <form class="post-form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <ul>
        {{ form.as_ul }}
        </ul>

        <button type="submit">Submit Tip</button>
      </form>
      {% endif %}

    </div>

  </div>
{% endblock content %}